/* Build web-sized WebP derivatives of every client photo.

   The masters in assets/images are 2048x1365 PNGs (~1.5MB each) — PNG is the wrong
   container for photographs, and nothing on the site displays them anywhere near
   that size. This mirrors them into assets/opt as WebP at two widths:

     -600   gallery tiles, service/gamme cards, thumbnails
     -1400  lightbox, hero posters, full-bleed and showcase stage

   Masters are never modified; re-run this whenever photos are added.

   Run: node scripts/optimize-media.js */
const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const ROOT = path.join(__dirname, '..');
const SRC_DIR = path.join(ROOT, 'assets', 'images');
const OUT_DIR = path.join(ROOT, 'assets', 'opt');

/* Already-derived folders: regenerated by their own scripts, skip. */
const SKIP_TOP = new Set(['opt', 'showcase', 'expertises']);

const SIZES = [
  { w: 600, q: 72, suffix: '-600' },
  { w: 1400, q: 78, suffix: '-1400' },
];

const isImage = f => /\.(png|jpe?g)$/i.test(f);

let made = 0, skipped = 0, srcBytes = 0, outBytes = 0;

async function convert(absSrc, relNoExt) {
  const stat = fs.statSync(absSrc);
  srcBytes += stat.size;

  const meta = await sharp(absSrc).metadata();
  for (const { w, q, suffix } of SIZES) {
    const dest = path.join(OUT_DIR, relNoExt + suffix + '.webp');
    fs.mkdirSync(path.dirname(dest), { recursive: true });

    /* Skip when the derivative is already newer than its master. */
    if (fs.existsSync(dest) && fs.statSync(dest).mtimeMs >= stat.mtimeMs) {
      outBytes += fs.statSync(dest).size;
      skipped++;
      continue;
    }
    await sharp(absSrc)
      .rotate()
      .resize({ width: Math.min(w, meta.width), withoutEnlargement: true })
      .webp({ quality: q, effort: 5 })
      .toFile(dest);
    outBytes += fs.statSync(dest).size;
    made++;
  }
}

async function walk(dir, rel) {
  for (const name of fs.readdirSync(dir)) {
    const abs = path.join(dir, name);
    const relPath = rel ? rel + '/' + name : name;
    if (fs.statSync(abs).isDirectory()) {
      if (!rel && SKIP_TOP.has(name)) continue;
      await walk(abs, relPath);
    } else if (isImage(name)) {
      await convert(abs, relPath.replace(/\.(png|jpe?g)$/i, ''));
    }
  }
}

(async () => {
  await walk(SRC_DIR, '');
  const mb = b => (b / 1048576).toFixed(1) + 'MB';
  console.log(`derivatives written: ${made}  (up to date: ${skipped})`);
  console.log(`masters  ${mb(srcBytes)}  ->  derivatives ${mb(outBytes)}  ` +
    `(${(100 - (outBytes / srcBytes) * 100).toFixed(1)}% smaller)`);
})().catch(e => { console.error(e); process.exit(1); });
